# !!! DO NOT MODIFY THIS FILE MANUALLY !!!
# File generated by 'setup_tf_backend.sh' dont modify this file manually
# unless you know what you are doing

terraform {
  backend "s3" {
    bucket         = "poc2-terraform-node-hw-tfstate-058264118467-us-east-1"
    key            = "states/poc2-terraform-node-hw/terraform.tfstate"
    region         = "us-east-1"
    dynamodb_table = "poc2-terraform-node-hw-terraform-lock-table"
    encrypt        = true
  }
}
