# !!! DO NOT MODIFY THIS FILE MANUALLY !!!
# File generated by 'setup_tf_backend.sh' dont modify this file manually
# unless you know what you are doing

variable "aws_region" {
  description = "AWS region for ECR repository"
  type        = string
  default     = "us-east-1"
}

variable "project_name_prefix" {
  description = "Prefix for the names of the aws resources to ensure uniqueness."
  type        = string
  default     = "poc2-terraform-node-hw"
}
