name: Deploy to AWS ECR

on:
  push:
    branches:
      - main

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  AWS_IAM_ROLE_ARN: ${{ secrets.AWS_IAM_ROLE_ARN }}

jobs:
  deploy:
    name: Deploy to ECR
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ env.AWS_IAM_ROLE_ARN }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: '1.12.0'

      - name: Terraform Init
        id: init
        run: terraform init -input=false
        working-directory: ./terraform

      - name: Terraform Apply
        id: apply
        run: terraform apply -auto-approve -input=false -var="AWS_REGION=${{ env.AWS_REGION }}"
        working-directory: ./terraform

      - name: Get ECR Repository URL
        id: get_ecr_url
        run: echo "ECR_REPOSITORY_URL=$(terraform output -raw ecr_repository_url)" >> $GITHUB_ENV
        working-directory: ./terraform
        # Esto hace que ECR_REPOSITORY_URL esté disponible como una variable de entorno (env.ECR_REPOSITORY_URL)
        # para los pasos siguientes.

      - name: Login to Amazon ECR
        id: login-ecr
        uses: docker/login-action@v3
        with:
          ecr:
            true # Usa automáticamente las credenciales de AWS configuradas en el paso anterior
            # y se loguea en el registro ECR para la AWS_REGION especificada.

      - name: Build, tag, and push image to Amazon ECR
        id: build-image
        uses: docker/build-push-action@v5
        with:
          context: . # El contexto de build es la raíz del repositorio
          file: ./Dockerfile # Ruta al Dockerfile
          push: true
          tags:
            ${{ env.ECR_REPOSITORY_URL }}:latest # Usa la URL del repo ECR obtenida de Terraform
            # ej: 123456789012.dkr.ecr.us-east-1.amazonaws.com/poc-hello-world-app:latest
